# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fe9b7f3a97c339a36b1cb63bae352abfa65ff75614eebf979bc8843d47c93f2eb9eaa3f97101a4285053dd40b22f7ce683b6553fbddeadd1965c1b021e44bd0

test:
  secret_key_base: 21fe0bbcf0732663043d8f848c4650e961f58c262ecaf8c11d59af5a17c654dbbc7608d8fa6235510a3ee3d31ac8e554999490f13645d713de277cda67379e51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
