require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BoughtMoviesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # boughtMovie. As you add validations to boughtMovie, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # boughtMoviesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bought_movies as @bought_movies" do
      bought_movie = BoughtMovie.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:bought_movies)).to eq([bought_movie])
    end
  end

  describe "GET show" do
    it "assigns the requested bought_movie as @bought_movie" do
      bought_movie = BoughtMovie.create! valid_attributes
      get :show, {:id => bought_movie.to_param}, valid_session
      expect(assigns(:bought_movie)).to eq(bought_movie)
    end
  end

  describe "GET edit" do
    it "assigns the requested bought_movie as @bought_movie" do
      bought_movie = BoughtMovie.create! valid_attributes
      get :edit, {:id => bought_movie.to_param}, valid_session
      expect(assigns(:bought_movie)).to eq(bought_movie)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new boughtMovie" do
        expect {
          post :create, {:bought_movie => valid_attributes}, valid_session
        }.to change(BoughtMovie, :count).by(1)
      end

      it "assigns a newly created bought_movie as @bought_movie" do
        post :create, {:bought_movie => valid_attributes}, valid_session
        expect(assigns(:bought_movie)).to be_a(boughtMovie)
        expect(assigns(:bought_movie)).to be_persisted
      end

      it "redirects to the created bought_movie" do
        post :create, {:bought_movie => valid_attributes}, valid_session
        expect(response).to redirect_to(BoughtMovie.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bought_movie as @bought_movie" do
        post :create, {:bought_movie => invalid_attributes}, valid_session
        expect(assigns(:bought_movie)).to be_a_new(BoughtMovie)
      end

      it "re-renders the 'new' template" do
        post :create, {:bought_movie => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end


  describe "DELETE destroy" do

    it "destroys the requested bought_movie" do
      bought_movie = BoughtMovie.create! valid_attributes
      expect {
        delete :destroy, {:id => bought_movie.to_param}, valid_session
      }.to change(BoughtMovie, :count).by(-1)
    end

  end

end
